// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tacnynltmlmgiuymenex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhY255bmx0bWxtZ2l1eW1lbmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NzAxODUsImV4cCI6MjA4NzU0NjE4NX0.Oel9ghTslfvTmjEKIkkMJqXqUI_8_gGlEQKL6OC1F5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});